# version: '3.1'

# services:
#  base_postgres:
#   image: postgres:16.1
#   container_name: base_postgres 
#   restart: always 
#   volumes:
#     - ./db:/var/lib/postgresql/data
#   environment:
#     - PDATA=/var/lib/postgresql/data/pgdata
#     - POSTGRES_USER=admin
#     - POSTGRES_PASSWORD=1234 
# ports:
#   9000:5432
# networks:
#   - postgres

#   base_pgadmin:
#     image: dpage/pgadmin4:7.8
#     container_name: base_pgadmin 
#     environment:
#       - PGADMIN_DEFAULT_EMAIL=ya@ya.ru
#       - PGADMIN_DEFAULT_PASSWORD=1234
#     volumes:
#       - ./pgadmin:/var/lib/pgadmin
#     ports:
#       - 9001:80
#     restart: unless-stopped 
#     networks:
#     - postgres

# networks: 
#   postgres:
#   name: bridge-mock-shop 
#     driver: bridge

# volumes:
#   postgres:
#   pgadmin:

version: "3.8"
services:
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"